// Edit user
export const FETCH_ALL_USERS = 'FETCH_ALL_USERS';
export const SET_ALL_USERS = 'SET_ALL_USERS';
export const ADD_USER_TO_EDIT = 'ADD_USER_TO_EDIT';

// Login
export const FETCH_USER_INFO = 'FETCH_USER_INFO';
export const SET_USER_INFO = 'SET_USER_INFO';
export const AUTH_USER = 'AUTH_USER';

// User actions
export const CREATE_USER = 'CREATE_USER';
export const UPDATE_USER = 'UPDATE_USER';
export const DELETE_USER = 'DELETE_USER';

// Curriculum
export const CREATE_CURRICULUM = 'CREATE_CURRICULUM';
export const SET_CURRICULUM_NAME = 'SET_CURRICULUM_NAME';
export const GET_CURRICULUMS = 'GET_CURRICULUMS';
export const SET_CURRICULUMS = 'SET_CURRICULUMS';
export const SET_CURRICULUM_TO_ASSIGN = 'SET_CURRICULUM_TO_ASSIGN';

// Courses
export const GET_ALL_COURSES = 'GET_ALL_COURSES';
export const SET_ALL_COURSES = 'SET_ALL_COURSES';
export const SET_COURSE = 'SET_COURSE';
export const UPDATE_COURSE = 'UPDATE_COURSE';
export const ADD_COURSE_TO_EDIT = 'ADD_COURSE_TO_EDIT';
export const SET_COURSES_TO_NAME = 'SET_COURSES_TO_NAME';
export const FETCH_COURSES_FOR_ONE_CURRICULUM = 'FETCH_COURSES_FOR_ONE_CURRICULUM';
export const SET_COURSES_TO_ASSIGN = 'SET_COURSES_TO_ASSIGN';
