// Login
export const FETCH_USER_INFO = 'FETCH_USER_INFO';
export const SET_USER_INFO = 'SET_USER_INFO';
export const AUTH_USER = 'AUTH_USER';

// Curriculum
export const CREATE_CURRICULUM = 'CREATE_CURRICULUM';
export const SET_CURRICULUM_NAME = 'SET_CURRICULUM_NAME';
export const GET_CURRICULUMS = 'GET_CURRICULUMS';
export const SET_CURRICULUMS = 'SET_CURRICULUMS';
export const SET_CURRICULUM_TO_ASSIGN = 'SET_CURRICULUM_TO_ASSIGN';
export const SET_CURRICULUM_TO_EDIT = 'SET_CURRICULUM_TO_EDIT';
export const UPDATE_CURRICULUM = 'UPDATE_CURRICULUM';

// Courses
export const GET_ALL_COURSES = 'GET_ALL_COURSES';
export const SET_ALL_COURSES = 'SET_ALL_COURSES';
export const SET_COURSE = 'SET_COURSE';
export const UPDATE_COURSE = 'UPDATE_COURSE';
export const ADD_COURSE_TO_EDIT = 'ADD_COURSE_TO_EDIT';
export const SET_COURSES_TO_NAME = 'SET_COURSES_TO_NAME';
export const FETCH_COURSES_FOR_ONE_CURRICULUM = 'FETCH_COURSES_FOR_ONE_CURRICULUM';
export const SET_COURSES_TO_ASSIGN = 'SET_COURSES_TO_ASSIGN';
export const DELETE_COURSE = 'DELETE_COURSE';
export const SET_PROFESSOR_TO_COURSE = 'SET_PROFESSOR_TO_COURSE';
export const REMOVE_PROF_FROM_COURSE = 'REMOVE_PROF_FROM_COURSE';
export const GET_ALL_EXCEPT_THESE_COURSES = 'GET_ALL_EXCEPT_THESE_COURSES';
export const SET_ALL_AVAILABLE_COURSES = 'SET_ALL_AVAILABLE_COURSES';

// Professors
export const GET_ALL_PROFESSORS = 'GET_ALL_PROFESSORS';
export const SET_ALL_PROFESSORS = 'SET_ALL_PROFESSORS';
export const CREATE_PROFESSOR = 'CREATE_PROFESSOR';
export const EDIT_PROFESSOR = 'EDIT_PROFESSOR';
export const UPDATE_PROFESSOR = 'UPDATE_PROFESSOR';
export const DELETE_PROFESSOR = 'DELETE_PROFESSOR';

// Roles
export const CREATE_ROLE = 'CREATE_ROLE';
export const FETCH_ALL_ROLES = 'FETCH_ALL_ROLES';
export const SET_ALL_ROLES = 'SET_ALL_ROLES';
export const ADD_ROLE_TO_EDIT = 'ADD_ROLE_TO_EDIT';
export const UPDATE_ROLE = 'UPDATE_ROLE';
export const DELETE_ROLE = 'DELETE_ROLE';
